import type { Plan } from "./schema";

/**
 * Plan catalog (Blueprint Part 11, market research 2026-09-19). Prices in paise,
 * before GST. These are PROPOSED list prices: confirm them against one week of
 * measured cost per minute before publishing (Blueprint Part 12). Limits of
 * null mean "no plan limit" (enterprise and government are set per contract).
 */
export const PLAN_CATALOG: Array<Omit<Plan, "updatedAt">> = [
  {
    key: "demo",
    name: "Demo",
    description: "A month to try it on real calls: 30 inbound and 30 outbound a day, then the plan has to change.",
    billingModel: "prepaid",
    monthlyFeePaise: 0,
    feeBasis: "per_workspace",
    includedMinutes: 0,
    overagePaisePerMin: null,
    limits: {
      branches: 1, phone_numbers: 1, concurrent_calls: 2, agents: 2, users: 5, campaigns_per_month: 2,
      inbound_calls_per_day: 30, outbound_calls_per_day: 30,
    },
    features: ["inbound_ai", "leads", "outbound_campaigns", "integrations"],
    isPublic: false,
    active: true,
    sort: 5,
  },
  {
    key: "trial",
    name: "Trial",
    description: "Try an AI receptionist on test calls before going live.",
    billingModel: "prepaid",
    monthlyFeePaise: 0,
    feeBasis: "per_workspace",
    includedMinutes: 150,
    overagePaisePerMin: null,
    limits: { branches: 1, phone_numbers: 1, concurrent_calls: 1, agents: 1, users: 3, campaigns_per_month: 0 },
    features: [],
    isPublic: true,
    active: true,
    sort: 10,
  },
  {
    key: "front_desk",
    name: "Front Desk",
    description: "One branch: AI receptionist answering every call, bookings, leads and owner dashboard.",
    billingModel: "prepaid",
    monthlyFeePaise: 299_900,
    feeBasis: "per_workspace",
    includedMinutes: 300,
    overagePaisePerMin: 700,
    limits: { branches: 1, phone_numbers: 1, concurrent_calls: 2, agents: 1, users: 5, campaigns_per_month: 0 },
    features: ["inbound_ai", "leads"],
    isPublic: true,
    active: true,
    sort: 20,
  },
  {
    key: "growth",
    name: "Growth",
    description: "Per branch: adds outbound reminders, recalls and follow-up campaigns, and sampled call QA.",
    billingModel: "prepaid",
    monthlyFeePaise: 799_900,
    feeBasis: "per_branch",
    includedMinutes: 1_200,
    overagePaisePerMin: 600,
    limits: { branches: 3, phone_numbers: 3, concurrent_calls: 5, agents: 3, users: 15, campaigns_per_month: 20 },
    features: ["inbound_ai", "leads", "outbound_campaigns", "ai_qa_sampled"],
    isPublic: true,
    active: true,
    sort: 30,
  },
  {
    key: "business",
    name: "Business",
    description: "Up to 5 branches, one number across branches, integrations, API and webhooks, QA on every call.",
    billingModel: "prepaid",
    monthlyFeePaise: 1_999_900,
    feeBasis: "per_workspace",
    includedMinutes: 4_000,
    overagePaisePerMin: 550,
    limits: { branches: 5, phone_numbers: 10, concurrent_calls: 15, agents: 10, users: 50, campaigns_per_month: 100 },
    features: ["inbound_ai", "leads", "outbound_campaigns", "ai_qa", "api_webhooks", "integrations", "multi_branch_number", "custom_voice"],
    isPublic: true,
    active: true,
    sort: 40,
  },
  {
    key: "enterprise",
    name: "Enterprise",
    description: "Hospitals and chains. Annual contract, committed minutes, SLA, dedicated success manager. Billed monthly against a PO.",
    billingModel: "contract",
    monthlyFeePaise: 0,
    feeBasis: "contract",
    includedMinutes: 0,
    overagePaisePerMin: null,
    limits: {},
    features: ["inbound_ai", "leads", "outbound_campaigns", "ai_qa", "api_webhooks", "integrations", "multi_branch_number", "custom_voice", "sla", "dedicated_success"],
    isPublic: true,
    active: true,
    sort: 50,
  },
  {
    key: "government",
    name: "Government",
    description: "Municipal and government bodies. Postpaid: a physical tax invoice every month against the work order or PO. India-only hosting, 1600-series, SLA.",
    billingModel: "postpaid_invoice",
    monthlyFeePaise: 0,
    feeBasis: "contract",
    includedMinutes: 0,
    overagePaisePerMin: null,
    limits: {},
    features: ["inbound_ai", "leads", "outbound_campaigns", "ai_qa", "api_webhooks", "integrations", "sla", "india_only", "series_1600", "dedicated_success"],
    isPublic: false,
    active: true,
    sort: 60,
  },
];

